### ISSUE TITLE
new metric: number of NULL references

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#10]
Let's add a new metric, which will calculate the number of `null` used in the code.

**Comment by RoukayaZaki** [comment]
I will start working on this issue @yegor256

**Comment by timur-harin** [comment]
@yegor256 
Is this issue still open?

I see that in 3ebc461 you already implemented it, isn't it?

**Comment by timur-harin** [comment]
@yegor256 
Please answer question above

**Comment by yegor256** [comment]
@timur-harin yes, it's fixed already
