### ISSUE TITLE
Make test doesn't work

### ISSUE THREAD

**Issue by padjal** [yegor256/cam#105]
After cloning the latest release in dataset/, `make test` doesn't work.
![Screenshot from 2023-10-12 15-07-46](https://github.com/yegor256/cam/assets/57331204/cbba4948-0586-4722-bbe9-a43b4e79a7ce)

**Comment by yegor256** [comment]
@padjal please, pull the changes from `master` and try again. You will see the log of the error. Post it here, we'll investigate further.

**Comment by padjal** [comment]
No log appears.
![image](https://github.com/yegor256/cam/assets/57331204/4fdba990-e558-424d-bbe8-b6d3882a3799)

**Comment by yegor256** [comment]
@padjal try again please

**Comment by padjal** [comment]
Here's the result
![image](https://github.com/yegor256/cam/assets/57331204/a6696a2f-c50f-4758-bfd5-653e57418670)

**Comment by padjal** [comment]
+ apt-get install -y xmlstarlet
        Reading package lists... Done
        Building dependency tree... Done
        Reading state information... Done
        The following packages were automatically installed and are no longer required:
          docker-scan-plugin libllvm13 libllvm13:i386 libvulkan1:i386 libwayland-client0:i386 mesa-vulkan-drivers:i386
        Use 'sudo apt autoremove' to remove them.
        The following NEW packages will be installed
          xmlstarlet
        0 to upgrade, 1 to newly install, 0 to remove and 13 not to upgrade.
        Need to get 265 kB of archives.
        After this operation, 631 kB of additional disk space will be used.
        Get:1 http://bg.archive.ubuntu.com/ubuntu jammy/universe amd64 xmlstarlet amd64 1.6.1-2.1 [265 kB]
        Fetched 265 kB in 0s (1,775 kB/s)  
        Selecting previously unselected package xmlstarlet.
        (Reading database ... 412341 files and directories currently installed.)
        Preparing to unpack .../xmlstarlet_1.6.1-2.1_amd64.deb ...
        Unpacking xmlstarlet (1.6.1-2.1) ...
        Setting up xmlstarlet (1.6.1-2.1) ...
        Processing triggers for man-db (2.10.2-1) ...
        + tlmgr option repository ctan
        (running on Debian, switching to user mode!)
        (see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)
        TLPDB: not a directory, not loading: /root/texmf
        tlmgr: user mode not initialized, please read the documentation!
        make: *** [Makefile:72: install] Error 2
        padjal@padjal ~/Documents/Dev/cam (master)$

**Comment by yegor256** [comment]
@padjal I'm closing this one, since it was resolved. If you any additional problems, please open new tickets
