### ISSUE TITLE
Number of Polymorphic Methods (NOP)

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#118]
Let's add NOP metric to `ast.py`, should be relatively easy to calculate. A method is "polymorphic" if there exists another method with the same name:

```
class Foo {
  void bar(int x) {} // polymorphic
  void bar(float x) {} // polymorphic
  void f(int z) {} // not polymorphic
}
```

**Comment by ocelot335** [comment]
When there are two subclasses of a class, and both contain a method with the same name, are these methods polymorphic?

**Comment by yegor256** [comment]
@ocelot335 I didn't understand the question. Can you give an example?

**Comment by ocelot335** [comment]
@yegor256 How many polymorphic methods should there be in the following cases in your opinion?
```
class Foo {
  calss A {
    int getF() {}
  }
  calss B {
    int getF() {}
  }
}
```
```
class Foo {
  calss A {
    int getF() {}
  }
  calss B extends A {
    int getF(int f) {}
  }
}
```

Also, if there "getF()" method in Parent? Should we ignore this? 
```
class Foo extends Parent{
  int getF(int f) {}
}
```

**Comment by yegor256** [comment]
@ocelot335 they are not "subclasses", they are "nested" classes: https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html (also known as inner or embedded).

I suggest we only count methods inside one class, ignoring parent classes.

**Comment by ocelot335** [comment]
@yegor256  Okay, did I understand correctly that NOP values will be 0 in appropriate cases?
```
class Foo {
  calss A {
    int getF() {}
  }
  calss B {
    int getF() {}
  }
}
```
```
class Foo {
  int getF() {}
  calss A {
    int getF() {}
  }
}
```

**Comment by yegor256** [comment]
@ocelot335 correct
