### ISSUE TITLE
Data vs Object Encapsulation Ratio (DOER)

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#126]
Inside `ast.py`, let's calculate the ratio between the number of attributes that are data primitives (int, float, String, Float, Double, Integer, etc.), and the number of attributes that are pointers to objects

**Comment by ocelot335** [comment]
How should we calculate this metric: 1) return (№dataPrimitive)/(№pointer), 2) (№dataPrimitive)/(№dataPrimitive+№pointer), 3) smth else? And are String, Integer, Float, Double primitives? They seem to just encapsulate primitives with methods for working with them. As written [there](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html): "The eight primitive data types supported by the Java programming language are: byte ... short ... int ... long ... float ... double ... boolean ... char"

**Comment by yegor256** [comment]
@ocelot335 let's calculate as `(№dataPrimitive)/(№dataPrimitive+№pointer)`. I suggest treating `Integer`, `Float` and others as pointers, since they exist exactly for that: add extra functionality to data primitives.

**Comment by padjal** [comment]
@yegor256 Issue is solved in #197. You can close it since it is no longer active.

**Comment by yegor256** [comment]
@padjal thanks!
