### ISSUE TITLE
Relative Age of File (RAF)

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#129]
Every file has the time of appearance in the repository. If we place all these values on a time line, the time of a given file will be somewhere in the middle. RAF is the number between 0 and 1, which shows where exactly is the file's time on the timeline.

**Comment by zaqbez39me** [comment]
@yegor256 Do I understand you correctly that you want to calculate the age of file relative to the time of the repository existence?
In example, repo was created in 2006 and the first appearance of a give file was in 2010. Now is 2024. Therefore, the age of the file is (2024 - 2010) / (2024 - 2006) ≈ 0.78.

**Comment by yegor256** [comment]
@zaqbez39me yes, this is correct

**Comment by zaqbez39me** [comment]
@yegor256 could you please verify that my pull request (#163) closes this issue?
