### ISSUE TITLE
snake_case variable names

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#132]
At the moment, the `varcomp` metric doesn't parse the following variable names correctly:

```
first_second (2)
helloWorld (2)
TESTNAME (1)
```

I think, the numbers after the names should be the values of `varcomp`

**Comment by yegor256** [comment]
@advasileva please, check this one if you have time

**Comment by evermake** [comment]
@yegor256, could you please check, whether my PR #161 closes this issue?

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.0`
