### ISSUE TITLE
Proposal: Introduce git pre-commit hooks for code quality analysis

### ISSUE THREAD

**Issue by pantafive** [yegor256/cam#16]
Pre-commit hooks should be performed by developers (automatically after `pre-commit install`) and as Github Actions pipeline.

**Comment by yegor256** [comment]
@pantafive we have GitHub action in this repo. What's missing?

**Comment by pantafive** [comment]
@yegor256, the core concept of this approach that you can run all linters before you commit (not even push) you code. And you can't (normally) omit that. Integrate pre-commit hooks into Github Actions is useful but not necessary. Take a look at this tool, it is great: https://pre-commit.com/ If you like it I can make common config and Action for it. During the project growth we can extend set of linters.

**Comment by yegor256** [comment]
@yegor256 we won't do this
