### ISSUE TITLE
delete non-UTF8 source Java files

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#169]

**Comment by timur-harin** [comment]
I started working on this problem

**Comment by timur-harin** [comment]
@yegor256 
In [PR](https://github.com/yegor256/cam/pull/173) I completed **deletion not UTF8 source Java files**

I think that **we need** also to have this **script** with showing which files were deleted which I put **in the help folder**

**Comment by timur-harin** [comment]
The using of this script is shown here
<img width="1095" alt="Screenshot 2024-02-27 at 19 30 33" src="https://github.com/yegor256/cam/assets/64702874/fdf7b666-146d-4dfa-96d5-2f4aac72cfb2">

The correct one with utf8 is here
<img width="749" alt="Screenshot 2024-02-27 at 19 32 40" src="https://github.com/yegor256/cam/assets/64702874/f406cb86-0252-4b5b-ba81-16ff30a85198">

**Comment by timur-harin** [comment]
@yegor256 I updated a PR with test and right position of script

**Comment by padjal** [comment]
@yegor256  I have created a [PR](https://github.com/yegor256/cam/pull/285) for this issue.

**Comment by padjal** [comment]
@yegor256 Since we have successfully merged PR #285 - Add delete wrongly encoded files, which solves this problem, I think that we can close this issue as well.

**Comment by padjal** [comment]
@yegor256 [PR#285](https://github.com/yegor256/cam/pull/285) with changes which solve this issue has been successfully merged. Please close this issue.
