### ISSUE TITLE
tlmgr error while installing 

### ISSUE THREAD

**Issue by timur-harin** [yegor256/cam#174]
@yegor256 looks like `sudo make install` may not work correct

`/root/cam/steps/install.sh: line 114: tlmgr: command not found`

<img width="645" alt="Screenshot 2024-02-27 at 22 21 20" src="https://github.com/yegor256/cam/assets/64702874/5e9fcba2-87e3-4e1b-8f25-9c22b55aa71f">

Related solving
https://tug.org/texlive/quickinstall.html
https://tug.org/texlive/upgrade.html

**Comment by yegor256** [comment]
@timur-harin should work now
