### ISSUE TITLE
Understandable errors while running ast.py

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#175]
While investigating `ast.py` I was trying to figure out to run it. I checked the code and only after that I figured out I have to provide the Java file and file for the output.

My suggestion: add "Usage" message for the case user run the file in a wrong way. It will allow user to start using the code without reading it.

Instead of having this:
<img width="744" alt="Screenshot 2024-02-28 at 20 36 43" src="https://github.com/yegor256/cam/assets/37439026/08faf4ca-340b-4e06-bc8d-a96ae6f1657d">

To have this:
<img width="687" alt="Screenshot 2024-02-28 at 20 38 16" src="https://github.com/yegor256/cam/assets/37439026/b635c18a-2534-4731-a301-c56d9c03175b">

**Comment by ilnarkhasanov** [comment]
@yegor256 can you approve this as an issue, please?

**Comment by yegor256** [comment]
@ilnarkhasanov definitely, would be great to have it. Also, we need a unit test to check whether the "Usage" is printed correctly.
