### ISSUE TITLE
The RAF is broken

### ISSUE THREAD

**Issue by zaqbez39me** [yegor256/cam#179]
The changes in tests were made together with logic changes. Now RAF time does not show relative time it actually shows real time of file  existence. Therefore, the time now not in range from 0 to 1.

**Comment by zaqbez39me** [comment]
@yegor256, please, check this issue

**Comment by yegor256** [comment]
@zaqbez39me it's still broken, but now for another reason: `sudo` is not the best command to use during unit testing. We need to find a better way.

**Comment by zaqbez39me** [comment]
@yegor256 fixed the issue with `sudo` usage
