### ISSUE TITLE
impossible to find more than 1000 repositories

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#186]
At the moment, there is a limitation in GitHub API: "search" can only retrieve up to 1000 repositories. Let's find a workaround, so that we can find more than 1000. See https://stackoverflow.com/questions/37602893/github-search-limit-results

**Comment by howcanunot** [comment]
I would suggest adding the `created={year}-01-01-01..{year}-12-31` parameter to the api query.
and starting from the current year (in descending order) make requests to the api
for example:
```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer {token}" \
  "https://api.github.com/search/repositories?q=language:Java+is:public+mirror:false+created:2021-01-01..2021-12-31+stars:400..10000" | grep 'total_count'
 ```
 we will get `"total_count": 203` which < 1000
 Eventually, iterating by year and then by page we can get >1000 repos

**Comment by howcanunot** [comment]
@yegor256 can i try to code this, please?

**Comment by yegor256** [comment]
@howcanunot sure, go ahead!

**Comment by lueFlake** [comment]
@yegor256 implemented it
