### ISSUE TITLE
Updating copyright

### ISSUE THREAD

**Issue by timur-harin** [yegor256/cam#189]
@yegor256 
It is necessary to update the copyright years in some files

For example:
~/paper/Makefile
~/fixtures/jaxec/pom.xml

**Comment by timur-harin** [comment]
Could I make PR with updating them?

**Comment by yegor256** [comment]
@timur-harin sure, go ahead. But we should not only update the year, but make sure that we don't have a similar problem in the future. Let's add a check into our `lint.sh` that will verify that all files have correct Copyright year. Similar to this, maybe: https://github.com/yegor256/iri/blob/master/Rakefile#L60-L64

**Comment by timur-harin** [comment]
I will take it

**Comment by padjal** [comment]
@yegor256  When do we run the `lint.sh` script and how do we alert if there is a problem?

**Comment by yegor256** [comment]
@padjal we just do `make lint`

**Comment by padjal** [comment]
@yegor256 Issue solved in PR #305
