### ISSUE TITLE
Understandable errors while running cyclomatic_complexity.py

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#200]
The output of running `cyclomatic_complexity.py` is unclear unless you check the code.

My suggestion is to have this output:
<img width="743" alt="Screenshot 2024-03-12 at 23 55 26" src="https://github.com/yegor256/cam/assets/37439026/8fa18154-83a2-4803-ac46-00ec115b53f0">

instead of having the current one:
<img width="885" alt="Screenshot 2024-03-12 at 23 52 06" src="https://github.com/yegor256/cam/assets/37439026/59ad9732-46ec-4b28-b122-de959e4f49e1">

**Comment by ilnarkhasanov** [comment]
@yegor256 could you approve this issue, please?

**Comment by yegor256** [comment]
@ilnarkhasanov let's fix this
