### ISSUE TITLE
Missing `to_h` cast in repo discovery script

### ISSUE THREAD

**Issue by howcanunot** [yegor256/cam#211]
if write `make dataset/repositories.csv` with `Total number of repositories to fetch from GitHub.` > 30 and % 100 != 0 we get an exception:
```
cam/steps/discover-repos.rb:125:in `<main>': undefined method `values' for an instance of Array (NoMethodError)
lines = [found.first[1].keys.join(',')] + found.values.map { |m| m.values.join(',') }
Did you mean?  values_at
```
This happens because if we exit the loop before we have collected enough repositories, the script tries to slice hash - [line with bug](https://github.com/yegor256/cam/blob/master/steps/discover-repos.rb#L105)

i suppose we miss `to_h` cast

**Comment by howcanunot** [comment]
@yegor256 fyi
noticed it when noticed it while I was working on https://github.com/yegor256/cam/issues/186

**Comment by yegor256** [comment]
fixed
