### ISSUE TITLE
calculate and show distribution of every metric, in the `report.tex`

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#216]
Let's get all metrics available in `all.csv` and render them one by one in graphs, into `report.tex`, in order to show distribution and some other values (mean, average, etc.)

**Comment by dzhovi** [comment]
@yegor256 i'd like split this issue into 2 sub-issues:

1. first one is about adding aggregation functionality (mean, average, etc.). and some tests on it.
2. (Correct me here if i misunderstood what you want to add to the final report) Second one is about adding table, where each row would represent particular metric, and it's columns would be aggregation functions.

**Comment by dzhovi** [comment]
@yegor256 could you close the issue?

**Comment by yegor256** [comment]
@dzhovi yes, thanks for the contribution!
