### ISSUE TITLE
Understandable error in `delete-non-classes.py`

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#218]
I suggest to have this message on wrong usage on `delete-non-classes.py`:

<img width="660" alt="image" src="https://github.com/yegor256/cam/assets/37439026/88f52fe9-cb4e-4460-af17-5e55a16eb5a5">

instead of the current one:

<img width="641" alt="image" src="https://github.com/yegor256/cam/assets/37439026/058750a0-5215-403f-af9f-43008a2187f5">

**Comment by yegor256** [comment]
@ilnarkhasanov go ahead
