### ISSUE TITLE
Understandable error in `delete-unparseable.py`

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#220]
I suggest to have this message in case of wrong usage:

<img width="658" alt="image" src="https://github.com/yegor256/cam/assets/37439026/1b1d9c61-e360-492c-ac29-96494b329abf">

instead of this one:

<img width="632" alt="image" src="https://github.com/yegor256/cam/assets/37439026/376166ba-e693-44b6-b98f-b0a710b81d17">

**Comment by ilnarkhasanov** [comment]
@yegor256 could you approve this issue, please?

**Comment by yegor256** [comment]
@ilnarkhasanov go ahead
