### ISSUE TITLE
Test fails on getset

### ISSUE THREAD

**Issue by padjal** [yegor256/cam#225]
Running the test-getset.sh with `make test TEST=tests/metrics/test-getset.sh` results in 
![image](https://github.com/yegor256/cam/assets/57331204/b961c304-28e5-4358-b3b3-b91644ce3381)

**Comment by yegor256** [comment]
@padjal this `test-getset.sh` file is not present in the repository, so we can't reproduce this bug. Let's discuss this problem in the PR, where this file is trying to be introduced.
