### ISSUE TITLE
filter out repositories with samples

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#227]
There are many popular repositories in Github, which contain Java tutorials and samples (for example: [leeowenowen/rxjava-examples](https://github.com/leeowenowen/rxjava-examples)). They are rather popular, that's why they get into our dataset. Would be great to find a way to filter them out at the `discover-repos.rb` script. Maybe by some Github tags that they usually have.

Maybe we can use some ML/LLM techniques for such a filtering (relying on the description of repositories and the content of their `README` files)?

This can help, maybe:

  * https://dl.acm.org/doi/pdf/10.1145/3084226.3084287
  * https://arxiv.org/pdf/2003.04755.pdf
  * https://link.springer.com/article/10.1007/s10664-018-9660-3
  * https://ink.library.smu.edu.sg/cgi/viewcontent.cgi?article=4616&context=sis_research

**Comment by h1alexbel** [comment]
@yegor256 please assign me

**Comment by yegor256** [comment]
@h1alexbel go ahead!
