### ISSUE TITLE
explain in report.tex how many repositories were compiled through Maven/Gradle

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#229]
Currently, it's not clear why some metrics (like LCOM5 and NHD) are not available for the majority of Java files. Let's explain this in the `report.tex` and provide statistics -- how many repositories were compiled and how many failed.

**Comment by Raleksan** [comment]
@yegor256 

Hi, is this question relevant at this time?

**Comment by yegor256** [comment]
@Raleksan yes, very relevant, please hlep

**Comment by Raleksan** [comment]
@yegor256 

Hi, I spent some time to think about this task and not invent adequate solution for it. May you explain in more details that you expect from me:
- Just finding repos with Maven/Gradle and note this number in report.
- Try to compile them, if success, then collect statistics, else note this in report.

**Comment by yegor256** [comment]
@Raleksan when we compile repos in order to calculate jpeek metrics (see `metrics/jpeek.sh`), we don't record the fact of whether the repo was compiled or not (success or failure). I suggest, we record it somewhere (in some additional file) and then use these files when we build the report in `report.sh`

**Comment by Raleksan** [comment]
@yegor256 

I investigated `metrics/jpeek.sh` and found that it just prints hard-coded metrics. Is there another way to collect metrics using `jpeek`?

I think I need to modify `steps/jpeek-repo.sh` to handle the repo compilation.

**Comment by yegor256** [comment]
@Raleksan you are right, we should modify `steps/jpeek-repo.sh`. [Here](https://github.com/yegor256/cam/blob/master/steps/jpeek-repo.sh#L47-L48), for example, we should not just log the problem but also record this fact somewhere (in some file).

**Comment by Raleksan** [comment]
@yegor256 

I think you can close this issue.
