### ISSUE TITLE
rename metrics to AllCaps format

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#237]
Let's make a test that will check that all metrics in the `metrics/` directory produce metric names that match this regexp: `^([A-Z][A-Za-z]*)+$`. Also, we will have to rename many metrics.

**Comment by MoromugHSE** [comment]
What should we do with metrics containing digits (LCOM5) or hyphens (SCOM-cvc, NHD-cvc...)? They don't match the regexp, yet it would be wrong to rename them, as it makes the output less understandable.

**Comment by MoromugHSE** [comment]
I decided to remove the hyphens and add digits to the regexp -- pull-request #261 now doesn't seem to be breaking anything!

**Comment by MoromugHSE** [comment]
@yegor256 some metrics we are getting from jPeek are suffixed with "-cvc" to explain that they are measured differently from the original ones -- do we have to rename them? Or would it be better to include that suffix in the regexp and leave them as-is?

**Comment by yegor256** [comment]
@MoromugHSE I suggest we renamed them to `LCOM5c`, etc.
