### ISSUE TITLE
explain metrics with more details

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#239]
Let's improve the details of some metrics:

  * DOER
  * FOUT
  * HSD, HSE, HSV
  * MIDX
  * NCSS
  * NULLS

Currently, they are very sketchy, which makes it hard to use them.

**Comment by LaithAlebrahim** [comment]
@yegor256 I'll work on it to details as mush as I can from those metrics

**Comment by LaithAlebrahim** [comment]
@yegor256 Just quick question , Should I document and details the code in ast.py or add the details to somewhere else.Thanks

**Comment by yegor256** [comment]
@LaithAlebrahim each of these metrics print their "details" as an output, for example in this line: https://github.com/yegor256/cam/blob/master/metrics/ast.py#L456 The output is `" Data vs Object Encapsulation Ratio"` -- this is not enough to understand what DOER metric is about. We should print a much more detailed explanation.

**Comment by dzhovi** [comment]
@yegor256 could you close the issue?
