### ISSUE TITLE
bug discovering metrics

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#245]
Let's try to add metrics that demonstrate how many bugs or vulnerabilities are visible by some tools in a Java class. We can use SpotBugs or PMD. Maybe, we can use Infer. Let's start with one simple tool and see how it works.

**Comment by Raleksan** [comment]
@yegor256 

Hi, can I take care of this problem?

**Comment by yegor256** [comment]
@Raleksan sure, go ahead!

**Comment by Raleksan** [comment]
@yegor256 

I think you can close this issue.

**Comment by yegor256** [comment]
@Raleksan thanks!
