### ISSUE TITLE
Integrate SonarCloud

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#247]
What I propose is integrating SonarCloud in the following steps:

1. I create a public project at sonarcloud.io
2. I add GitHub Actions workflow and other configurations to the PR
3. I send you a token for a SonarCloud in a safe way
4. You create a `SONAR_TOKEN` secret as a repository owner
5. We merge PR
6. We're done!

**Comment by ilnarkhasanov** [comment]
@yegor256 could you approve the issue, please?

**Comment by yegor256** [comment]
@ilnarkhasanov I created the project in Sonarcloud.io and set the secret `SONAR_TOKEN` to the right value. Please, continue.

**Comment by yegor256** [comment]
@ilnarkhasanov I believe, it works now
