### ISSUE TITLE
Remove commented code snippets

### ISSUE THREAD

**Issue by ilnarkhasanov** [yegor256/cam#251]
SonarCloud [catched](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=yegor256_cam2&open=AY6DeMabLl2Ddm3rvjy0) 2 code snippets that are recommended to be removed.

**Comment by ilnarkhasanov** [comment]
@yegor256 could you approve this issue, please?

**Comment by yegor256** [comment]
@ilnarkhasanov indeed, let's fix
