### ISSUE TITLE
Texlive test fails

### ISSUE THREAD

**Issue by padjal** [yegor256/cam#254]
The `help/test-texlive-bin.sh` test fails to finish:

<img width="486" alt="image" src="https://github.com/yegor256/cam/assets/57331204/3fcdfd91-bc02-4b2c-987c-819a918f6a7d">

**Comment by yegor256** [comment]
@padjal did you run `make install` successfully on your machine?

**Comment by padjal** [comment]
@yegor256 `make install` also doesn't finish without errors:
<img width="438" alt="image" src="https://github.com/yegor256/cam/assets/57331204/1c6282c5-cd61-4b88-b8c8-03f7d4763953">

**Comment by yegor256** [comment]
@padjal either install Java on your machine or try to use Docker, as explained in README

**Comment by padjal** [comment]
What is the recommended way to install tlmgr? 
<img width="669" alt="image" src="https://github.com/yegor256/cam/assets/57331204/be977a93-54ae-4e69-abfb-39d10db71493">

**Comment by yegor256** [comment]
@padjal try it one more time, we updates installation scripts. Do `sudo make install`

**Comment by padjal** [comment]
Seems like you have fixed this issue. Can be closed.
