### ISSUE TITLE
allow certain suffixes of metric names and forbid prefixes

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#266]
Now, the `test-measure.sh` test is checking the formatting of metric names. It only allows AllCaps format. Let's make it even stricter. Let's introduce the following rules: if `Mn`, `Mx` or `Av` is used in the name, it should finish the name. Thus, `CoCoMn` is right, `MnCoCo` is wrong.

**Comment by zaqbez39me** [comment]
@yegor256 sorry, I cannot find any formatting tests in `test-measure.sh`. Could you, please, say where it is done in the script?

**Comment by LaithAlebrahim** [comment]
@zaqbez39me ,Sorry I already took it  but waiting for another task to be merged so I can make other PR to not mix tasks commits,
Sorry for inconvienent and not making comment here.

**Comment by LaithAlebrahim** [comment]
I made PR for this issue.
Could you please check it here: https://github.com/yegor256/cam/pull/269
Thanks @yegor256

**Comment by yegor256** [comment]
@LaithAlebrahim thanks for solving this one!
