### ISSUE TITLE
Refactor If Statements

### ISSUE THREAD

**Issue by tanmaysharma2001** [yegor256/cam#271]
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=yegor256_cam2&open=AY6DeMZuLl2Ddm3rvjyz

**Comment by tanmaysharma2001** [comment]
@yegor256 Approve this issue please!

**Comment by yegor256** [comment]
@tanmaysharma2001 definitely a bug, please help to fix

**Comment by tanmaysharma2001** [comment]
@yegor256 done!
