### ISSUE TITLE
`make install` fails with unknown error

### ISSUE THREAD

**Issue by h1alexbel** [yegor256/cam#276]
I try to build a repository to start working with it (setup Python, Ruby), running this command:

```bash
$ make install
```

as README states here
https://github.com/yegor256/cam/blob/6d10816ad2ccad71a4b363a176a2fe636b295abf/README.md?plain=1#L121

However, the installation fails with an unknown error:

```text
+++ install +++

+ '[' -n '' ']'
+ '[' -n '' ']'
+ install_package parallel
+ local PACKAGE=parallel
+ eval parallel --version
+ '[' -n '' ']'
+ echo 'Install '\''parallel'\'' somehow'
Install 'parallel' somehow
+ exit 1
make: *** [install] Error 1
```

Also, what is the right way to set up and test the repository so that I can add my logic on top of it?

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Comment by yegor256** [comment]
@h1alexbel this means that you should install `parallel`, it's a Unix tool: https://www.gnu.org/software/parallel/parallel_tutorial.html

**Comment by h1alexbel** [comment]
@yegor256 thanks, now it works
