### ISSUE TITLE
let's replace the hardcoded number of expected values with calculated in `test-measure-file.sh`

### ISSUE THREAD

**Issue by zaqbez39me** [yegor256/cam#282]
The number of expected metrics that should be obtained during `measure-file.sh` executed is hardcoded right now. This can lead to conflict during adding new metric in repo. For example, two developers will add two more metrics in separate pull requests and eacho of them will increase the counter of metrics by 1. If both pull requests will be accepted we will face with the conflict during the merging with `master` branch, which is bad. Let's, somehow, make the expected number of metrics calculated to avoid cases mentioned above.

**Comment by zaqbez39me** [comment]
@yegor256 I just found out that this number cannot be easily calculated. However, we can store somewhere the expected number  of metrics for each metric script. Is it good idea? If yes, where it is better to store them

**Comment by yegor256** [comment]
@zaqbez39me maybe let's just change the test: make it check that the number of metrics found is _greater or equal_ to some number.

**Comment by zaqbez39me** [comment]
@yegor256 ok, but this tolerance may make the the tests unsafe with future changes. Maybe, we should apply greater or equal in separate PR without closing this issue for now?

**Comment by yegor256** [comment]
@zaqbez39me yes, let's do it

**Comment by timur-harin** [comment]
@yegor256
I think we need to close this issue, because PR merged success

**Comment by yegor256** [comment]
@zaqbez39me we fixed it. If you don't mind, I'm closing
