### ISSUE TITLE
add Halstead metrics

### ISSUE THREAD

**Issue by IlyaPechersky** [yegor256/cam#291]
In addition to the completely banal classical quantitative metrics, I also propose to add Halstead metrics (at least the most basic ones to begin with).

Halstead metrics are a system for evaluating program performance that measures the complexity and size of code. Such metrics are a more advanced version of assessing complexity and labor costs than the standard SLOC.

[How to calculate](https://www.geeksforgeeks.org/software-engineering-halsteads-software-metrics/)

**Comment by IlyaPechersky** [comment]
@yegor256 please, verify this suggestion

If we need it, I'll take it to work

**Comment by yegor256** [comment]
@IlyaPechersky I believe, we already have them, calculated by Multimetric: https://github.com/yegor256/cam/blob/master/metrics/multimetric.sh#L36-L38

**Comment by IlyaPechersky** [comment]
Oh, I see, thank you!
