### ISSUE TITLE
Incorrect calculation of some metrics in the case when there is more than one non-nested class in the java file (cam-2022-02-17.zip)

### ISSUE THREAD

**Issue by Nypiaka** [yegor256/cam#30]
On the example of the attributes, sattributes, methods, smethods metrics, you can see that the analyzer's work is incorrect in the case described in the header. For example, if you open the "WindowStateAnimator.java" file, you can see two classes in one java file. For this case, the calculation of metrics is incorrect. It is necessary to write (include?) a filter.

**Comment by yegor256** [comment]
@Nypiaka I guess #31 fixes this
