### ISSUE TITLE
put CaM sources into a ZIP archive

### ISSUE THREAD

**Issue by yegor256** [yegor256/cam#308]
When packaging all together, let's put CaM sources into it too. This will make the dataset more "reproducible."

**Comment by Raleksan** [comment]
Hi, I would like to take on this issue.

Can you clarify following questions:
1. Would it be fine to implement this operation in `cam/steps/zip.sh`?
2. Do I need truncate the history of cloning repository?

**Comment by yegor256** [comment]
@Raleksan sure, go ahead please! Yes, it should be implemented in the `zip.sh`. I think it would be reasonable to remove the history (remote the `.git` directories).
