### ISSUE TITLE
PEP 8: E501 line too long (129 > 120 characters) in ast.py

### ISSUE THREAD

**Issue by nikzor** [yegor256/cam#319]
@yegor256 
In `ast.py` file in repository we get warning from linter: "PEP 8: E501 line too long (129 > 120 characters)" in line 32 https://github.com/yegor256/cam/blob/428b12f04de249ff8f009c2199d9b947695dbf43/metrics/ast.py#L32
I suggest to fix it

**Comment by nikzor** [comment]
@yegor256 
Please, check this PR #320

**Comment by nikzor** [comment]
@yegor256 
If you will agree, I can add new workflow with flake8 checker, that will check Python code and provide information about Python warnings

**Comment by yegor256** [comment]
@nikzor yes, let's do it

**Comment by nikzor** [comment]
@yegor256 
Is it better to do it in different issue?

**Comment by nikzor** [comment]
@yegor256 
I believe that it makes no sense to consider problems related to the length of the string, since there are enough places in the repository code where we exceed 79 characters (this is the current value according to PEP8, without Pycharm overrides). However, this does not directly affect the quality of the code. However, flake8 provides an opportunity to check Python code in detail according to the writing convention, so adding this linter will help improve the repository in the future. The error E501 can be added to the exceptions, as it does not make much sense.

**Comment by yegor256** [comment]
@nikzor I agree! please, submit a PR

**Comment by yegor256** [comment]
@nikzor I believe, this is fixed
