### ISSUE TITLE
The latest version of CAM is not going without a VPN.

### ISSUE THREAD

**Issue by Nypiaka** [yegor256/cam#32]
`tlmgr: package repository https://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/systems/texlive/tlnet (not verified: unknown)
tlmgr install: package already present: footmisc
tlmgr install: package already present: latexmk
[1/40, ??:??/??:??] install: anyfontsize [182k]
TLPDB::_install_data: downloading did not succeed (download_file failed) for https://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/systems/texlive/tlnet/archive/anyfontsize.tar.xz
[2/40, 04:52/45:46:22] install: arphic [26908k]`

but if turn VPN on, files will be download successfully

**Comment by yegor256** [comment]
@Nypiaka this problem is not related to the project, it's related to your local environment
