### ISSUE TITLE
PEP 8: E501 line too long (129 > 120 characters) in cyclomatic_complexity.py

### ISSUE THREAD

**Issue by nikzor** [yegor256/cam#321]
@yegor256
In `cyclomatic_complexity.py` file in repository we get warning from linter: "PEP 8: E501 line too long (129 > 120 characters)" in line 41
https://github.com/yegor256/cam/blob/428b12f04de249ff8f009c2199d9b947695dbf43/metrics/cyclomatic_complexity.py#L41
I suggest to fix it

**Comment by nikzor** [comment]
@yegor256 
Please, check this PR #322

**Comment by nikzor** [comment]
@yegor256 
This issue might be deleted, PyCharm overrides default PEP8 rules, so that actual PEP8 maximum line length is 79, not 120

**Comment by yegor256** [comment]
@nikzor ok
