### ISSUE TITLE
TexLive install error handling

### ISSUE THREAD

**Issue by timur-harin** [yegor256/cam#333]
@yegor256

If interrupt installing TeXLive - we will have folder and source, but command will not work because name occupied already unzipped file

```bash
The directory with TeXLive does exist (/usr/local/texlive/2024/bin/universal-darwin), but 'tlmgr' doesn't run, can't understand why :(
+ wget --quiet http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
+ unzip install-tl.zip -d install-tl
Archive:  install-tl.zip
replace install-tl/install-tl-20240519/install-tl? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
make: *** [install] Error 1
```

Install script does not handle it

Do you think we need to fix it?

**Comment by yegor256** [comment]
@timur-harin yes, definitely, let's remove the `install-tl` directory before `unzip`

**Comment by timur-harin** [comment]
@yegor256 
Ok, I will do it

**Comment by timur-harin** [comment]
@yegor256 
Let's also add check if install-tl.zip already here

Do you want:
- Remove it always before wget 
- Not remove and install if already here
?

**Comment by timur-harin** [comment]
@yegor256 
In PR #335 you can see that I implemented way that if we already have install-tl.zip -> skip wget

**Comment by timur-harin** [comment]
@yegor256 
Could you please check it?

**Comment by timur-harin** [comment]
@yegor256 
I think we can close this issue because PR #335 merged
