### ISSUE TITLE
make install fails on MacOS

### ISSUE THREAD

**Issue by nai1ka** [yegor256/cam#356]
`sudo make install` fails on MacOS 14.6, because installing brew packages as a root is no longer supported

<img width="825" alt="Screenshot 2024-09-03 at 11 36 49" src="https://github.com/user-attachments/assets/093d6d89-aa43-49d5-ba3d-fb6c0c9d7c1d">

**Comment by nai1ka** [comment]
Moreover, `install-pip fails` because of [externally-managed-environment error](https://dev.to/luca1iu/how-to-fix-the-externally-managed-environment-error-when-using-pip-2omo#:~:text=This%20error%20occurs%20because%20your,to%20avoid%20conflicts%20or%20issues.)



<img width="805" alt="Screenshot 2024-09-06 at 21 07 58" src="https://github.com/user-attachments/assets/5998559c-d843-421f-91da-d65126bf1d37">

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`
