### ISSUE TITLE
Uninstaller tool

### ISSUE THREAD

**Issue by nai1ka** [yegor256/cam#373]
@yegor256 , what do you think about adding an uninstaller tool? `cam` installs many apps (e.g. TeX-Live, Inkscape, parallel etc.) and I think it would be nice to have such a feature.

**Comment by yegor256** [comment]
@nai1ka this would be pretty dangerous, I believe. We will have to remove a lot of system-level packages. Maybe, instead, we can print a detailed message when `make install` happens? Some sort of a warning: `"You are going to install these packages: ... Do you agree?"` Then, the user should click `Yes` (or call it like this: `make install FORCE_INSTALL=yes`)
