### ISSUE TITLE
Adding venv activation to the README

### ISSUE THREAD

**Issue by dzhovi** [yegor256/cam#383]
Readme suggests to run script that generates metrics for a repo [in the following way](https://github.com/yegor256/cam#:~:text=make%20clean%0Amake%20REPO%3Dyegor256/tojos):

what i got is the error indicating that some of the modules were not installed, [like here](https://github.com/yegor256/cam/issues/375). That problem can be fixed simply by activating virtual environment, which is generated by  `make install`.
In my opinion, activating virtual environment is not so obvious for those, who are not familiar with python. I suggest to add steps of activating `venv` to the README. 

The same story for [that code snippet](https://github.com/yegor256/cam#:~:text=sudo%20make%20install%0Asudo%20make%20test%20lint). it needs activation of venv too

**Comment by dzhovi** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@dzhovi sure, feel free to submit a pull request
