### ISSUE TITLE
After one hour, the build broke down

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/cam#47]
I was trying to build `cam` docker image in order to try the tool locally. Hence, I run the next command:
```sh
docker build --tag=cam .
```
And after one hour `Building 3714.3s (24/26) ` build was failed:
```
 => ERROR [17/19] RUN cd /usr/local &&   wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.37.0/pmd-bin-6.37.0.zip &&   unzip pmd-bin-6.37.0.zip &&   rm pmd-bin-6.37.0.zip &&   mv pmd-bin-6  0.0s
------
 > [17/19] RUN cd /usr/local &&   wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.37.0/pmd-bin-6.37.0.zip &&   unzip pmd-bin-6.37.0.zip &&   rm pmd-bin-6.37.0.zip &&   mv pmd-bin-6.37.0 pmd &&   ln -s /usr/local/pmd/bin/run.sh /usr/local/bin/pmd:

failed to prepare qujy5iugcx1hc9odep4c9lxjm: max depth exceeded

```

The full log right here:
[cam.fail.log](https://github.com/yegor256/cam/files/12281977/cam.fail.log)

**Comment by volodya-lombrozo** [comment]
@yegor256 Do you know where could be a problem?

**Comment by yegor256** [comment]
@volodya-lombrozo `max depth exceeded` means this: https://stackoverflow.com/questions/47272611/docker-max-depth-exceeded

Try to switch to `yegor256/rultor-image:1.21.0` in https://github.com/yegor256/cam/blob/master/Dockerfile
